CREATE TABLE EMP1(
EMPNO			int			NOT NULL		PRIMARY KEY,
ENAME			char(200)	NOT NULL,
MGR				int			NOT NULL,
HIREDATE		date		NOT NULL,
DEPTNO			int			NOT NULL,
);

CREATE TABLE DEPT(
DEPTNO			int			NOT NULL		PRIMARY KEY,
DNAME			char(200)	NOT NULL,
LOC				char(200)	NOT NULL,
);

SELECT * FROM EMP1

UPDATE EMP1 
SET DEPTNO = 30 WHERE ENAME = 'BLAKE'

INSERT INTO EMP1(EMPNO, ENAME, MGR, HIREDATE, DEPTNO)
VALUES(7499, 'ALLEN', 7698, '20-02-1981', 30)

SELECT * FROM DEPT

INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES(10, 'ACCOUNTING', 'NEW YORK')

---------------------------------
SELECT * FROM EMP1 AS e
INNER JOIN DEPT AS d ON e.DEPTNO = d.DEPTNO
WHERE d.LOC = 'CHICAGO'


SELECT e.ENAME'Name', e.HIREDATE 'HireDate', f.ENAME 'BOSS' FROM 
EMP1 AS e INNER JOIN DEPT AS d ON e.DEPTNO = d.DEPTNO
INNER JOIN EMP1 as f ON e.MGR = f.EMPNO
WHERE d.LOC = 'CHICAGO'


				
